/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package asaderosadonox;

/**
 *
 * @author Gerardo
 */
import javax.swing.*;

public class Clientes extends javax.swing.JDialog {

    /**
     * Creates new form Clientes
     */
    public Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Conexion.mostrarClientes(t_clientesPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_clientesPrincipal = new javax.swing.JTable();
        b_eliminarCliente = new javax.swing.JButton();
        b_editarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        t_clientesPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Domicilio", "Telefono", "Referencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_clientesPrincipal);
        if (t_clientesPrincipal.getColumnModel().getColumnCount() > 0) {
            t_clientesPrincipal.getColumnModel().getColumn(0).setResizable(false);
            t_clientesPrincipal.getColumnModel().getColumn(0).setPreferredWidth(20);
            t_clientesPrincipal.getColumnModel().getColumn(1).setResizable(false);
            t_clientesPrincipal.getColumnModel().getColumn(1).setPreferredWidth(120);
            t_clientesPrincipal.getColumnModel().getColumn(2).setResizable(false);
            t_clientesPrincipal.getColumnModel().getColumn(2).setPreferredWidth(120);
            t_clientesPrincipal.getColumnModel().getColumn(3).setResizable(false);
            t_clientesPrincipal.getColumnModel().getColumn(4).setResizable(false);
        }

        b_eliminarCliente.setText("Eliminar");
        b_eliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_eliminarClienteMouseClicked(evt);
            }
        });

        b_editarCliente.setText("Editar");
        b_editarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_editarClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_editarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_eliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_eliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_editarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_eliminarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_eliminarClienteMouseClicked
        int columnaIdCliente = 0;
        int row = t_clientesPrincipal.getSelectedRow();
        int clienteAEliminar = Integer.parseInt(t_clientesPrincipal.getModel().getValueAt(row, columnaIdCliente).toString());
        Conexion.eliminarCliente(clienteAEliminar);
        Conexion.mostrarClientes(t_clientesPrincipal);
    }//GEN-LAST:event_b_eliminarClienteMouseClicked

    private void b_editarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_editarClienteMouseClicked
        int columnaIdCliente = 0;
        int columnaNombre = 1;
        int columnaDomicilio = 2;
        int columnaTelefono = 3;
        int columnaReferencia = 4;
        
        int selectedRow = t_clientesPrincipal.getSelectedRow();
        
        int id_cliente = Integer.parseInt(t_clientesPrincipal.getModel().getValueAt(selectedRow, columnaIdCliente).toString());
        String nombre = t_clientesPrincipal.getModel().getValueAt(selectedRow, columnaNombre).toString();
        String domicilio = t_clientesPrincipal.getModel().getValueAt(selectedRow, columnaDomicilio).toString();
        String telefono = t_clientesPrincipal.getModel().getValueAt(selectedRow, columnaTelefono).toString();
        String referencia = t_clientesPrincipal.getModel().getValueAt(selectedRow, columnaReferencia).toString();
                
        String nuevoNombreTemp = new JOptionPane().showInputDialog("Nombre Actual: "+nombre+"\n"+"Ingrese el Nuevo Nombre: ");
        String nuevoDomicilioTemp = new JOptionPane().showInputDialog("Domicilio Actual: "+domicilio+"\n"+"Ingrese el Nuevo Domiclio: ");
        String nuevoTelefonoTemp = new JOptionPane().showInputDialog("Telefono Actual: "+telefono+"\n"+"Ingrese el Nuevo Telefono: ");
        String nuevaReferenciaTemp = new JOptionPane().showInputDialog("Nombre Actual: "+referencia+"\n"+"Ingrese la Nueva Referencia: ");
        
        String nuevoNombre = "";
        String nuevoDomicilio = "";
        String nuevoTelefono = "";
        String nuevaReferencia = "";
        
        if(!nuevoNombreTemp.isEmpty()){
            nuevoNombre = nuevoNombreTemp;
        }
        else{
            nuevoNombre = nombre;
        }
        if(!nuevoDomicilioTemp.isEmpty()){
            nuevoDomicilio = nuevoDomicilioTemp;
        }
        else{
            nuevoDomicilio = domicilio;
        }
        if(!nuevoTelefonoTemp.isEmpty()){
            nuevoTelefono = nuevoTelefonoTemp;
        }
        else{
            nuevoTelefono = telefono;
        }
        if(!nuevaReferenciaTemp.isEmpty()){
            nuevaReferencia = nuevaReferenciaTemp;
        }
        else{
            nuevaReferencia = referencia;
        }
        
        Conexion.editarCliente(id_cliente, nuevoNombre, nuevoDomicilio, nuevoTelefono, nuevaReferencia);
        Conexion.mostrarClientes(t_clientesPrincipal);
    }//GEN-LAST:event_b_editarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_editarCliente;
    private javax.swing.JButton b_eliminarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_clientesPrincipal;
    // End of variables declaration//GEN-END:variables
}
